### PR TITLE
Update of the tags

### PR DESCRIPTION
**Pull request by SergioLangaritaBenitez**
M13 Delete CreateLaunchConfiguration, DeleteLaunchConfiguration, EstimateTemplateCost from PL_CF
M14 Delete AddTagsToResource from PL_APP
M15 Delete AddPermission20150331v2 from PL_LAMBDA_SQS
Update of Readme

### CODE REVIEW

**Comment by gmolto** [comment]
upload build

**Comment by micafer** [comment]
test this please

**Comment by micafer** [comment]
upload build

**Comment by micafer** [comment]
upload build

**Pull request merged**
